"""Add description column to FoundItem and LostItem

Revision ID: 0c6d5ffe5f35
Revises: dc4307138591
Create Date: 2025-06-16 19:48:10.439525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6d5ffe5f35'
down_revision = 'dc4307138591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('found_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lost_item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'found_item', ['found_item_id'], ['id'])
        batch_op.create_foreign_key(None, 'lost_item', ['lost_item_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'found_item', ['item_id'], ['id'])
        batch_op.drop_column('lost_item_id')
        batch_op.drop_column('found_item_id')

    # ### end Alembic commands ###