"""Add storage_location column to found_item

Revision ID: 35a7c7206e7e
Revises: 41e90b57cf17
Create Date: 2025-05-17 18:28:09.718144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a7c7206e7e'
down_revision = '41e90b57cf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('storage_location')

    # ### end Alembic commands ###
