"""Added acquisition_time to FoundItem

Revision ID: 41e90b57cf17
Revises: 
Create Date: 2025-05-14 18:57:53.388362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e90b57cf17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquisition_time', sa.String(length=100), nullable=False))
        batch_op.drop_column('item_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_description', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('acquisition_time')

    # ### end Alembic commands ###
