"""Add category column to found_item

Revision ID: 6495b006cef8
Revises: 35a7c7206e7e
Create Date: 2025-05-17 18:50:00.190859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6495b006cef8'
down_revision = '35a7c7206e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
