"""Add description field

Revision ID: dc4307138591
Revises: 6495b006cef8
Create Date: 2025-06-16 19:32:21.709958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4307138591'
down_revision = '6495b006cef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('lost_location', sa.String(length=100), nullable=False),
    sa.Column('lost_by_name', sa.String(length=100), nullable=False),
    sa.Column('lost_by_contact', sa.String(length=100), nullable=False),
    sa.Column('lost_time', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_filename', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'found_item', ['item_id'], ['id'])
        batch_op.drop_column('item_type')

    op.drop_table('lost_item')
    # ### end Alembic commands ###
